name: ci

on:
  push:
    tags:
      - 'v*'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: hannahwysong/wysong-ceg3120:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./angular-site/angular-bird/wsu-hw-ng-main
          file: ./angular-site/angular-bird/wsu-hw-ng-main/Dockerfile
	  push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ secrets.DOCKER_USERNAME }}/wysong-ceg3120:latest


